### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by kentchang84** [HansSchouten/PHPageBuilder#11]
Successfully installed with composer. Manage to enter website manager and create a page but failed to load pagebuilder with error "page not found". Please help.

**Comment by electroheadfx** [comment]
because you need to put the apache rewriting with an .htaccess, take the one in src and setup like you like, for local I removed the https route.

**Comment by HansSchouten** [comment]
Are you using the [boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate)?

**Comment by skerbis** [comment]
I have the same problem. I use the boilerplate. I just get "page not found". 
Testing on a real Domain, not local.

**Comment by skerbis** [comment]
@kentchang84 check config and hosting-setting that you use only www. oder Domain without www.

**Comment by kentchang84** [comment]
I'm using boilerplate install with composer at local environment. I found my problem was using misconfiguration in config.php and .htaccess. I'm able to load now but only saw 1 'Hello World' element, is it correct?

**Comment by skerbis** [comment]
Yes, there is only one template.

**Comment by HansSchouten** [comment]
Yep at the moment you need to create the other blocks yourself, by pasting HTML snippets in view files like I did in the example block. I hope I have soon some time to create a bootstrap theme.
