### ISSUE TITLE
Installing with Composer, do not include latest updates from master branch

### ISSUE THREAD

**Issue by treborin** [HansSchouten/PHPageBuilder#124]
I made an install with Composer: `composer require hansschouten/phpagebuilder`
But latest Pull requests are not included there. It`s not the same code as the master branch.
**Keep that in mind if you use Composer**

**Comment by Demonicious** [comment]
I think that's just because the master branch is considered "unstable" - And the new changes haven't been released as a version yet.

**Comment by HansSchouten** [comment]
I just created a new release: https://github.com/HansSchouten/PHPageBuilder/releases/tag/v0.22.0
