### ISSUE TITLE
 Loading pagebuilder

### ISSUE THREAD

**Issue by electroheadfx** [HansSchouten/PHPageBuilder#13]
All are setup but when I edit a page, I have a pagebuilder loader loading endless, I have no error, is grappejs need to be setup ? or its need some template libraries ? thanks

**Comment by HansSchouten** [comment]
Hi I know about this issue in previous releases, can you double check that you are running on the latest release? And do you see any errors in your browser console?

**Comment by electroheadfx** [comment]
yes I updated your last fix on save-page.js file, no error in console
![Capture d’écran 2020-05-17 à 17 44 39](https://user-images.githubusercontent.com/1211149/82153180-416d7500-9866-11ea-9223-a6bf5d7fc801.png)

I dont know if it help. Iam on safari, maybe do you want I check in others browser ?

**Comment by HansSchouten** [comment]
Yes that would be great. I did not manage to run Safari on my Windows machine as it seems there is no supported version anymore.

**Comment by electroheadfx** [comment]
I tested in Firefox, it sound like a X-Content-Type-Options?: 
![Capture d’écran 2020-05-17 à 18 15 03](https://user-images.githubusercontent.com/1211149/82153887-8f847780-986a-11ea-86a6-1bc837ad25b9.png)
![Capture d’écran 2020-05-17 à 18 15 12](https://user-images.githubusercontent.com/1211149/82153891-91e6d180-986a-11ea-98d9-35073d2e48bb.png)

**Comment by electroheadfx** [comment]
For chrome seem the error are more detailed:
![Capture d’écran 2020-05-17 à 18 44 39](https://user-images.githubusercontent.com/1211149/82154493-b17ff900-986e-11ea-954b-ae5b8c11dd49.png)
![Capture d’écran 2020-05-17 à 18 44 54](https://user-images.githubusercontent.com/1211149/82154494-b349bc80-986e-11ea-9703-7890150dc36a.png)

**Comment by HansSchouten** [comment]
Thanks for the details, the content type warning I have seen before. Will fix it in the next release. However, the amazonaws.com link is unrelated to the pagebuilder to my knowledge. I have not seen that URL before.

**Comment by electroheadfx** [comment]
I tried again the issue still there, I tried all browser, maybe if you like test online on my server : http://efxdesign.fr/pagebuilder/admin
user : admin
pass : lolo123
there is the same issue.

**Comment by HansSchouten** [comment]
I checked your files and the content of your [app.js](http://efxdesign.fr/pagebuilder/home/efxdesign/config/assets/pagebuilder/app.js) is not the same as in the [latest release](https://github.com/HansSchouten/PHPageBuilder/releases/tag/v0.11.0).

**Comment by HansSchouten** [comment]
Aha I see you are in sync with the master, so it is not related to script versions. However, I see that [pageinjection.js](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/assets/js/page-injection.js) is never loaded. This script is responsible for triggering an event from the page that is edited to the pagebuilder that the loading has been finished. I am trying to figure out why this happens in your environment.

**Comment by HansSchouten** [comment]
[Here](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/assets/js/manage-editable-components.js#L15) the page injection script is automatically added to the end of your page body. Could you verify that you are using a layout with a valid html structure, like this [in the boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate/blob/master/themes/demo/layouts/master/view.php).

**Comment by electroheadfx** [comment]
wow it was the issue, only a echo body was in the template.

Did you know now how I can grab some page builder elements now ? the pagebuilder templates looks like empty :)

![Capture d’écran 2020-05-18 à 08 59 52](https://user-images.githubusercontent.com/1211149/82183423-3f4afb00-98e6-11ea-9b5a-d1a69dd588df.png)

**Comment by HansSchouten** [comment]
Glad to hear that it is working now! About the page builder elements you can do a quick read to an earlier conversation I had here: https://github.com/HansSchouten/Laravel-Pagebuilder/issues/8#issuecomment-625752907. In short: an example Bootstrap theme is coming, but I didn't have time for it yet as I am using this project to deliver some projects to clients now. In the meantime you can see the correct structure [over here](https://github.com/HansSchouten/PHPagebuilder-boilerplate/tree/master/themes/demo) and create the html blocks you desire.
