### ISSUE TITLE
ckeditor add align option

### ISSUE THREAD

**Issue by electroheadfx** [HansSchouten/PHPageBuilder#15]
How I can add align options (center, left, right) to ckeditor with your implementation? I tried to tweak your grapjs config (pluginsOpts/gjs-plugin-ckeditor/options/toolbar) I had not success
thanks

**Comment by HansSchouten** [comment]
I remember I have tried that before, but after adding the CKEditor text align buttons it did not work. In the meanwhile a number of CKEditor related stuff has changed so I will give it a try again soon.

**Comment by HansSchouten** [comment]
I added text align buttons to the style sidebar
![afbeelding](https://user-images.githubusercontent.com/5946444/84682208-99ff6300-af35-11ea-8c4e-19525ab88a81.png)
