### ISSUE TITLE
Cannot redeclare phpb_registered_assets() (previously declared in /Applications/MAMP/htdocs/vendor/hansschouten/phpagebuilder/src/Core/helpers.php:573)

### ISSUE THREAD

**Issue by GrandM1961** [HansSchouten/PHPageBuilder#152]
I got this error and don't know what to do

**Comment by HansSchouten** [comment]
Thanks for reporting the issue, standard steps would be to search through the project for phpb_registered_assets in this case. In line helpers.php line 566 it checked a different name than was shown in line 573. I just pushed a commit to fix it.
