### ISSUE TITLE
Add new page setting half blank

### ISSUE THREAD

**Issue by pixelmode** [HansSchouten/PHPageBuilder#154]
Just downloaded this project. Couldn't get it working at first as it forces you to use a www in the URL which was driving me crazy. 
 The demo page doesn't seem to show up but will render a thumbnail.  But the one issue I found is that when adding a new page 
 the settings page renders part way down the form and errors out. The **page-meta-title** and **page-meta-description** form fields in page-settings.php try to use a function named **e** instead of **phpb_e**. Correcting that fixes the issue.

I haven't pushed a change to a project outside my own on git for a while so listing here instead.

**Comment by HansSchouten** [comment]
Thanks for reporting the issue, I just pushed a commit replacing `e()` by `phpb_e()`.
