### ISSUE TITLE
Blocks are missing?

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#17]
Just deployed your Laravel package on clean Laravel

having this in edit window
![image](https://user-images.githubusercontent.com/1683476/83794817-36f50d00-a6a7-11ea-9234-8d634b01b0a9.png)

am I missing something? 
your screenshot looks much better (much blocks on the left)
![image](https://user-images.githubusercontent.com/1683476/83794940-67d54200-a6a7-11ea-8ddd-9e0182212df7.png)

**Comment by HansSchouten** [comment]
Hi, it looks like your installation went perfect! In the screenshot you see how I used the project to create a website with very specific blocks that you probably do not need. These are not just html image and text elements, but very specific snippets of a premium theme that I bought. This project aimes to give a programmer full freedom to create your own custom websites with any customizable component that you want. Other builders often come with pre-defined blocks and very limited functionality to add/modify these. So (especially in this early stage), this project is not aiming to help anyone to build the same looking website. Instead, it is a tool to allow building and maintaining any website with your own custom blocks. 

Creating your own blocks is very easy. Each block has just a simple .html or a .php file and that's it. Creating blocks is just a matter of tearing an awesome [HTML5 theme](https://themeforest.net/category/site-templates?sort=sales&tags=html5#content) apart into small snipets (i.e. blocks) and you're done.

That being said, I can imagine that is still not always pleasant to do this for a quick and simple website, so I am planning to create a default theme based on bootstrap that has blocks for each bootstrap component.

**Comment by imagina** [comment]
hummm... same question here,. it would be great to have a default theme like in the screenshot so we have a real start or demo to play around or connect with our install...
can we buy this or other premium theme for your package ? It would be great! Thanks @HansSchouten

**Comment by san8work** [comment]
How to clear blocks cache?
I deleted some blocks but they still showing.
