### ISSUE TITLE
Getting error in localhost server

### ISSUE THREAD

**Issue by Sarveshmrao** [HansSchouten/PHPageBuilder#19]
I'm not able to go to the admin interface in the localhost server. I use WAMP as my local server and I installed as said in the readme file I ave also installed the boiler plate as said. Please help with this issue I already went through issues but nothing works

**Comment by HansSchouten** [comment]
Did you correctly set up the `config.php` file, with `app_url` set to `https://localhost:8080` or similar depending on your URL? And do you see any errors and do you see a "page not found" if you go to the `/` page instead of `/admin` page.

**Comment by Sarveshmrao** [comment]
Hi, thanks for the fast reply. 
1. There is nothing call app_url in the config.php there is base_url and I changed it. 
2. When I go / I can see a page where it has 2 links one to the admin and another to GitHub. 
3. When I go to /admin it redirects me to www.localhost which gives an error saying localhost actively refused your connection
Thanks!!!

**Comment by HansSchouten** [comment]
Ah yeah you're right, I meant base_url and the default page is also correct. I added that recently.
The error "localhost actively refused your connection" I have not seen before, but [it seems](https://stackoverflow.com/questions/9695224/no-connection-could-be-made-because-the-target-machine-actively-refused-it-127-0#answer-9695442) a webserver related issue. But also the url www.localhost is strange. Can you share the config you are using? And what is the exact URL you are trying to reach, is it just http://localhost/admin ?

**Comment by mansmahamat** [comment]
Hello i have the same problem with internal server of laravel when i do php artisan serve http://127.0.0.1:8000/admin i have page error

**Comment by Sarveshmrao** [comment]
Thank you so much for your reply!
I have all the files at localhost/sysinfo and I use WAMP
and I am trying to go to http://localhost/sysinfo/admin but it redirects me to https://www.localhost (notice the protocol change)

My server config hope this helps you
```
Server Configuration
Apache Version: 2.4.41
Server Software: Apache/2.4.41 (Win64) PHP/7.3.12 - Port defined for Apache: 80
PHP Version: 7.3.12
MariaDB Version: 10.4.10 - Port defined for MariaDB: 3306 - Default DBMS
MySQL Version: 8.0.18 - Port defined for MySQL: 3308
```
I use MySQL and i have mentioned port 3308 in the config.php and I have a database named sysinfo with the tables you gave.


Here is my config.php
```
<?php

return [`
  /*
   |--------------------------------------------------------------------------
    | General settings
     |--------------------------------------------------------------------------
     |
     |`General settings for configuring the PageBuilder.
     |
     */
    'general' => [
        'base_url' => 'http://localhost/sysinfo',
        'language' => 'en',
        'assets_url' => '/assets',
        'uploads_url' => '/uploads'
    ],

    /*
     |--------------------------------------------------------------------------
     | Storage settings
     |--------------------------------------------------------------------------
     |
     | Database and file storage settings.
     |
     */
    'storage' => [
        'use_database' => true,
        'database' => [
            'driver'    => 'mysql',
            'host'      => 'localhost:3308',
            'database'  => 'sysinfo',
            'username'  => 'root',
            'password'  => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
        'uploads_folder' => __DIR__ . '/uploads'
    ],

    /*
     |--------------------------------------------------------------------------
     | Auth settings
     |--------------------------------------------------------------------------
     |
     | By default an authentication class is provided which checks for the
     | credentials configured in this setting block.
     |
     */
    'auth' => [
        'use_login' => true,
        'class' => PHPageBuilder\Modules\Auth\Auth::class,
        'url' => '/admin/auth',
        'username' => 'admin',
        'password' => 'changethispassword'
    ],

    /*
     |--------------------------------------------------------------------------
     | WebsiteManager settings
     |--------------------------------------------------------------------------
     |
     | By default a basic WebsiteManager is provided for creating/editing pages.
     |
     */
    'website_manager' => [
        'use_website_manager' => true,
        'class' => PHPageBuilder\Modules\WebsiteManager\WebsiteManager::class,
        'url' => '/admin'
    ],

    /*
     |--------------------------------------------------------------------------
     | Website settings
     |--------------------------------------------------------------------------
     |
     | By default a setting class is provided for accessing website settings.
     |
     */
    'setting' => [
        'class' => PHPageBuilder\Setting::class
    ],

    /*
     |--------------------------------------------------------------------------
     | PageBuilder settings
     |--------------------------------------------------------------------------
     |
     | By default a PageBuilder is provided based on GrapesJS.
     |
     */
    'pagebuilder' => [
        'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
        'url' => '/admin/pagebuilder',
        'actions' => [
            'back' => '/admin'
        ]
    ],

    /*
     |--------------------------------------------------------------------------
     | Page settings
     |--------------------------------------------------------------------------
     |
     | By default a Page class is provided with knowledge about its layout and URL.
     |
     */
    'page' => [
        'class' => PHPageBuilder\Page::class,
        'table' => 'pages',
        'translation' => [
            'class' => PHPageBuilder\PageTranslation::class,
            'table' => 'page_translations',
            'foreign_key' => 'page_id',
        ]
    ],

    /*
     |--------------------------------------------------------------------------
     | Theme settings
     |--------------------------------------------------------------------------
     |
     | PageBuilder requires a themes folder in which for each theme the individual
     | theme blocks are defined. A theme block is a sub folder in the themes folder
     | containing a view, model (optional) and controller (optional).
     |
     */
    'theme' => [
        'class' => PHPageBuilder\Theme::class,
        'folder' => __DIR__ . '/themes',
        'folder_url' => '/themes',
        'active_theme' => 'demo'
    ],

    /*
     |--------------------------------------------------------------------------
     | Routing settings
     |--------------------------------------------------------------------------
     |
     | Settings for resolving pages based on the current URI.
     |
     */
    'router' => [
        'class' => PHPageBuilder\Modules\Router\DatabasePageRouter::class
    ],

    /*
     |--------------------------------------------------------------------------
     | Class replacements
     |--------------------------------------------------------------------------
     |
     | Allows mapping a class namespace to an alternative namespace,
     | useful for replacing implementations of specific pagebuilder classes.
     | Example: PHPageBuilder\UploadedFile::class => Alternative\UploadedFile::class
     | Important: when overriding a class always extend the original class.
     |
     */
    'class_replacements' => [
    ],
]; 
```

This is the page I get when I go to http://localhost/sysinfo/ (This is where the package is)
![2020-06-30](https://user-images.githubusercontent.com/49156390/86078349-8d3d4c00-baab-11ea-9a15-4a05909fcea7.png)

And when I go over the get started button it shows localhost/sysinfo/admin
But when I click it redirects me to https://www.localhost and this is the error I get!
![2020-06-30 (1)](https://user-images.githubusercontent.com/49156390/86078449-cecdf700-baab-11ea-9978-98d61f4ee75b.png)

and here is my .htaccess file
I removed couple of lines in the start seeing some old issues here then only I was able to access the index page.

```
<IfModule mod_rewrite.c>
    RewriteEngine On


    # Remove any trailing slashes from non-directories using a redirect
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [R=301,L]

    # Rewrite /themes/{theme}/{file} to /themes/{theme}/public/{file}
    RewriteRule ^themes/([^/]+)/(?!public/)(.*)$ themes/$1/public/$2 [L]

    # Rewrite non-directory and non-file URLs to index.php
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Allow accessing files with URLs in format /themes/{theme}/public/{file}
    RewriteRule ^themes/([^/]+)/public/(.*)$ themes/$1/public/$2 [L]

    # Rewrite all remaining requests to index.php
    RewriteRule ^ index.php [L]
</IfModule>
```

My file structure in localhost/sysinfo/

```
sysinfo
|
|
|---- PHPageBuilder
|          |
|          |----- Files from this repo
|
|---- PHPagebuilder-boilerplate
|          |
|          |----- Files from the boilerplate repo
|
|---- themes
|           |----demo
|                 |----some files out here from the boilerplate
|
|---- .htaccess
|
|---- config.php
|
|---- index.php
|
|---- readme.md
|
|---- some files for my project is out here
|
----end----
```

Thanks!!!

**Comment by HansSchouten** [comment]
Thanks for the elaborate details, this helps debugging a lot. I see you have a folder `PHPagebuilder-boilerplate`, this is not what I am using. The files of this folder should be in your `/sysinfo` folder.

**Comment by Sarveshmrao** [comment]
Yeah actually the PHPagebuilder-boilerplate is empty. Sorry for that..

**Comment by HansSchouten** [comment]
Ok, the rest looks good to me. Can you try to set a few breakpoints in this main method: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/PHPageBuilder.php#L242. I am curious whether it redirects before it enters, then I will be webserver/.htaccess related.

Also try to restart your server and try another browser (in incognito mode), to see if it makes a difference.

**Comment by Sarveshmrao** [comment]
Surprisingly it works in Microsoft Edge Browser's Latest version but and also on Incognito Tab in Google Chrome. But does not work in the normal Google Chrome tab. I think its some Extension conflicting.

**Comment by Sarveshmrao** [comment]
If you want to close this issue just close it off. I'm keeping this open because if you want you can ask me anything further. Thanks for your support. BTW can we use [this blocks](https://froala.com/design-blocks/)  in the editor

**Comment by Sarveshmrao** [comment]
Now I am getting this. I created a page and clicked edit and it's loading for the past 8-10 mins


![2020-06-30 (2)](https://user-images.githubusercontent.com/49156390/86093002-ee751780-bacb-11ea-8e5b-507ae907dc2c.png)

**Comment by HansSchouten** [comment]
Thanks for the great suggestion, clean UI blocks which are very easy to import. I will make sure these blocks come available.

Loading the pagebuilder should take at most 3sec, so I suspect there are JavaScript errors in your case. Can you show what your browser console outputs?

**Comment by Sarveshmrao** [comment]
Here is the screenshot of my console. Hope this helps you. 

![2020-07-01](https://user-images.githubusercontent.com/49156390/86197599-5a5e8b00-bb73-11ea-91fe-6379197bca65.png)

**Comment by HansSchouten** [comment]
Ok, so debugging with the browser console really helps.

In the next error you show I also don't see any causes, so I just followed the error message and opened [Theme:51](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Theme.php#L51) and it tries to open your theme's blocks folder. So the next thing to check is, do you have this folder?

**Comment by Sarveshmrao** [comment]
Yes I have it in localhost/themes/demo/blocks
Inside it there is only hello-world folder

**Comment by HansSchouten** [comment]
Your project's root directory is `www/sysinfo/`, so your themes folder should be in there as well.

**Comment by Sarveshmrao** [comment]
@HansSchouten If I move the themes files inside sysinfo I get this error
![error](https://user-images.githubusercontent.com/49156390/86197599-5a5e8b00-bb73-11ea-91fe-6379197bca65.png)
if I move that folder to www then I get the other error.

**Comment by HansSchouten** [comment]
Here you see exactly which files should be in your `sysinfo` folder: https://github.com/HansSchouten/PHPagebuilder-boilerplate.

Can you show a screenshot of that folder?

**Comment by Sarveshmrao** [comment]
This is my sysinfo folder. (Highlighted files are my project files).
![2020-07-03 (1)](https://user-images.githubusercontent.com/49156390/86456184-51221980-bd3f-11ea-9ff2-421d306f33ca.png)
This is my www folder.
![2020-07-03 (2)](https://user-images.githubusercontent.com/49156390/86456190-52ebdd00-bd3f-11ea-86b3-dfc205856c2e.png)

**Comment by HansSchouten** [comment]
You should drag your `themes` folder into your `sysinfo` folder.

**Comment by Sarveshmrao** [comment]
This is the error I get if I move it inside the sysinfo folder.

![2020-07-05](https://user-images.githubusercontent.com/49156390/86530753-1b189d00-bed9-11ea-9a45-d7f0aa026f16.png)

**Comment by HansSchouten** [comment]
I think your `general.base_url` config is not correct. You use `http://localhost/sysinfo/` to access your website right? And PHPageBuilder is trying to load the theme files from `http://localhost/...`

**Comment by Sarveshmrao** [comment]
Sarveshmrao comented 6 days ago
>............
> 
> Here is my config.php
> 
> ```
> <?php
> 
> return [`
>   /*
>    |--------------------------------------------------------------------------
>     | General settings
>      |--------------------------------------------------------------------------
>      |
>      |`General settings for configuring the PageBuilder.
>      |
>      */
>     'general' => [
>         'base_url' => 'http://localhost/sysinfo',
>         'language' => 'en',
>         'assets_url' => '/assets',
>         'uploads_url' => '/uploads'
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Storage settings
>      |--------------------------------------------------------------------------
>      |
>      | Database and file storage settings.
>      |
>      */
>     'storage' => [
>         'use_database' => true,
>         'database' => [
>             'driver'    => 'mysql',
>             'host'      => 'localhost:3308',
>             'database'  => 'sysinfo',
>             'username'  => 'root',
>             'password'  => '',
>             'charset'   => 'utf8',
>             'collation' => 'utf8_unicode_ci',
>             'prefix'    => '',
>         ],
>         'uploads_folder' => __DIR__ . '/uploads'
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Auth settings
>      |--------------------------------------------------------------------------
>      |
>      | By default an authentication class is provided which checks for the
>      | credentials configured in this setting block.
>      |
>      */
>     'auth' => [
>         'use_login' => true,
>         'class' => PHPageBuilder\Modules\Auth\Auth::class,
>         'url' => '/admin/auth',
>         'username' => 'admin',
>         'password' => 'changethispassword'
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | WebsiteManager settings
>      |--------------------------------------------------------------------------
>      |
>      | By default a basic WebsiteManager is provided for creating/editing pages.
>      |
>      */
>     'website_manager' => [
>         'use_website_manager' => true,
>         'class' => PHPageBuilder\Modules\WebsiteManager\WebsiteManager::class,
>         'url' => '/admin'
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Website settings
>      |--------------------------------------------------------------------------
>      |
>      | By default a setting class is provided for accessing website settings.
>      |
>      */
>     'setting' => [
>         'class' => PHPageBuilder\Setting::class
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | PageBuilder settings
>      |--------------------------------------------------------------------------
>      |
>      | By default a PageBuilder is provided based on GrapesJS.
>      |
>      */
>     'pagebuilder' => [
>         'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
>         'url' => '/admin/pagebuilder',
>         'actions' => [
>             'back' => '/admin'
>         ]
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Page settings
>      |--------------------------------------------------------------------------
>      |
>      | By default a Page class is provided with knowledge about its layout and URL.
>      |
>      */
>     'page' => [
>         'class' => PHPageBuilder\Page::class,
>         'table' => 'pages',
>         'translation' => [
>             'class' => PHPageBuilder\PageTranslation::class,
>             'table' => 'page_translations',
>             'foreign_key' => 'page_id',
>         ]
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Theme settings
>      |--------------------------------------------------------------------------
>      |
>      | PageBuilder requires a themes folder in which for each theme the individual
>      | theme blocks are defined. A theme block is a sub folder in the themes folder
>      | containing a view, model (optional) and controller (optional).
>      |
>      */
>     'theme' => [
>         'class' => PHPageBuilder\Theme::class,
>         'folder' => __DIR__ . '/themes',
>         'folder_url' => '/themes',
>         'active_theme' => 'demo'
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Routing settings
>      |--------------------------------------------------------------------------
>      |
>      | Settings for resolving pages based on the current URI.
>      |
>      */
>     'router' => [
>         'class' => PHPageBuilder\Modules\Router\DatabasePageRouter::class
>     ],
> 
>     /*
>      |--------------------------------------------------------------------------
>      | Class replacements
>      |--------------------------------------------------------------------------
>      |
>      | Allows mapping a class namespace to an alternative namespace,
>      | useful for replacing implementations of specific pagebuilder classes.
>      | Example: PHPageBuilder\UploadedFile::class => Alternative\UploadedFile::class
>      | Important: when overriding a class always extend the original class.
>      |
>      */
>     'class_replacements' => [
>     ],
> ]; 
> ```
>...........

See this comment!!! Where I have attached the config file.

**Comment by HansSchouten** [comment]
Hmm you are right, that is correct. I don't have a clue why it is sending requests to `/themes/..` instead of `/sysinfo/themes/...`.

**Comment by Sarveshmrao** [comment]
Wow!!! @HansSchouten thank you so much it worked the problem was with the theme_url.. thanks.

**Comment by HansSchouten** [comment]
Great, glad to hear it is solved! However, I would regard this as a bug from my end. The themes folder should be relative to the configured `base_url`. I will keep this issue open untill I've solved that.

**Comment by Sarveshmrao** [comment]
Ok sure! Anyways a very great software!!! but where are the pages saved?

**Comment by HansSchouten** [comment]
Thanks! Pages are saved in the `pages` table. You can configure this also in your `config.php`.

**Comment by kwserp** [comment]
In my case the admin page works fine, but when I create the page and click on view I get 'Page not found'.
I found this error in [PHPageBuilder.php#L284](https://github.com/HansSchouten/PHPageBuilder/blob/ce575d8666dd199a2ac1e23c082bcd0565a3e746/src/PHPageBuilder.php#L284)

**Comment by HansSchouten** [comment]
Is your page route in the format: `/test`, so starting with a slash?

**Comment by kwserp** [comment]
Yes, my page rout is with slash.
Website Manager work fine. All data stored in db correctly. 
The procedure I used:
1) Add new page in website manager
2) Setting page 
    In "Url" I was try full urll: http://localhost/www/phpbuilder/test
   and short url: /test
3) Edit page
    I was create sample "Hallo world!" page and save it

When I click the "view" button in pagebuilde I got "Page not found".
The same thing happens when I try to see a page from a website manager.

**Comment by HansSchouten** [comment]
Please check your config settings. The `base_url` should be `http://localhost/www/phpbuilder` in your case. However, also double check your webserver environmnt. In 10+ years I never had to use URLs like that. This is error prone as well. The www folder name usually is not something that comes back in your URL.

**Comment by kwserp** [comment]
I use XAMPP on my local PC. I created a "www" folder to test the scripts.
This script works well on a server. With small code corrections, I was able to customize it to work on my local PC.
