### ISSUE TITLE
Create Tutorial

### ISSUE THREAD

**Issue by KaleemBhatti** [HansSchouten/PHPageBuilder#28]
Hi dear,
Please create complete tutorial of this without tutorial we can't create this project it's may help us thanks.

**Comment by HansSchouten** [comment]
Unfortunately at the moment I don't have time to write more complete tutorials/documentation. This project is currently mostly useful for programmers that don't mind looking up how something works inside the original source code (which is quite well-structured and not that much code). However, I aim to answer any specific questions that might arise.

**Comment by Entretoize** [comment]
+1 really needs a tutorial it's really too complicated !
