### ISSUE TITLE
theme's css file doesn't load 

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#29]
@HansSchouten Need your help again

![image](https://user-images.githubusercontent.com/1683476/96166288-71f53000-0f26-11eb-946b-2214b9fafbfe.png)

as I understood correctly I have a link in my "themes/main/layouts/master/view.php"

`<link rel="stylesheet" href="[theme-url]/css/style.css" />`

and style.css file located at themes/main/public/css/style.css

but browser shows nothing on this link: https://mysite/themes/main/css/style.css

any thoughts?

here is my tree
![image](https://user-images.githubusercontent.com/1683476/96165833-d5329280-0f25-11eb-9434-61da772ab9f9.png)

**Comment by dsultanr** [comment]
I have the "themes" folder in my Laravel project's root. Not in public folder. Seems that it should be inside a webroot folder (public)?

**Comment by HansSchouten** [comment]
Hmm strange, this is indeed how I am using it. Maybe an issue with your .htaccess file? It should strip the /public/ part from the URL.

**Comment by dsultanr** [comment]
yep, I did not alter the .htaccess file. thanks
