### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by leonp5** [HansSchouten/PHPageBuilder#30]
Hi,
thanks for sharing your work.

I'm running it on a ubuntu server 18.04.

I'm not sure, where my fault is, but i only get a blank page with the text "Page not found". At the root of the domain and also on `/admin`.
First i forgot to copy the `confing.php` into the webroot folder. But after i did, run the `.sql` file and edited the config it seems, that i've everything done, you described.
What could be the problem?

**Comment by HansSchouten** [comment]
The page not found is triggered at various locations in this file: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/PHPageBuilder.php

It triggers when _phpb_in_module()_ is not matched for any of the pagebuilder modules.

Can you add some debug output [here](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Core/helpers.php#L301) to check why it does not detect the modules.

**Comment by leonp5** [comment]
@HansSchouten thanks for your answer :+1: 

Output of `$url` in the `helpers.php`: `string(11) "/admin/auth" `

Output of `$currentUrl` in the `helpers.php`: `string(8) "/lfe.com"`

There seems to be a fault. The domain is: `test.e-hilfe.com`

**Comment by HansSchouten** [comment]
Can you list the contents of your config, maybe there is an issue over there?

**Comment by parmando** [comment]
Do we have a solution?
I have the same problem here:
https://www.otimo.site/

**Comment by parmando** [comment]
I think there's something wrong with .htaccess ...
Here is an echo "hello world!"; and even that doesn't work:
https://www.otimo.site/hello.php

**Comment by parmando** [comment]
Detail I don't have the composer installed, would that be?

**Comment by HansSchouten** [comment]
We don't have a solution since there is not yet any debug output. I don't have this issue myself so I cannot solve it right now.

It should work just fine without composer. Can you try this:
> Can you list the contents of your config, maybe there is an issue over there? Especially the general -> base_url.
>
>Or else try debugging this method, which generated the $currentUrl: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Core/helpers.php#L240

**Comment by parmando** [comment]
See in:
https://www.otimo.site/

I added echo phpb_current_full_url (); in index.php

**Comment by leonp5** [comment]
> Can you list the contents of your config, maybe there is an issue over there? Especially the `general -> base_url`.
> 
> Or else try debugging this method, which generated the `$currentUrl`: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Core/helpers.php#L240

Do you mean this config?

Or where do i find the `general->base_url`?

```
  GNU nano 2.9.3                                                                                                                                                                                                                                                                                                           config.php                                                                                                                                                                                                                                                                                                                      

        'class' => PHPageBuilder\Modules\Auth\Auth::class,
        'url' => '/admin/auth',
        'username' => 'admin',
        'password' => '*****'
    ],

    /*
     |--------------------------------------------------------------------------
     | WebsiteManager settings
     |--------------------------------------------------------------------------
     |
     | By default a basic WebsiteManager is provided for creating/editing pages.
     |
     */
    'website_manager' => [
        'use_website_manager' => true,
        'class' => PHPageBuilder\Modules\WebsiteManager\WebsiteManager::class,
        'url' => '/admin'
    ],

    /*
     |--------------------------------------------------------------------------
     | Website settings
     |--------------------------------------------------------------------------
     |
     | By default a setting class is provided for accessing website settings.
     |
     */
    'setting' => [
        'class' => PHPageBuilder\Setting::class
    ],

    /*
     |--------------------------------------------------------------------------
     | PageBuilder settings
     |--------------------------------------------------------------------------
     |
     | By default a PageBuilder is provided based on GrapesJS.
     |
     */
    'pagebuilder' => [
        'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
        'url' => '/admin/pagebuilder',
        'actions' => [
            'back' => '/admin'
        ]
    ],

    /*
     |--------------------------------------------------------------------------
     | Page settings
     |--------------------------------------------------------------------------
     |
     | By default a Page class is provided with knowledge about its layout and URL.
     |
     */
    'page' => [
        'class' => PHPageBuilder\Page::class,
        'table' => 'pages',
        'translation' => [
            'class' => PHPageBuilder\PageTranslation::class,
            'table' => 'page_translations',
            'foreign_key' => 'page_id',
        ]
    ],

    /*
     |--------------------------------------------------------------------------
     | Theme settings
     |--------------------------------------------------------------------------
     |
     | PageBuilder requires a themes folder in which for each theme the individual
     | theme blocks are defined. A theme block is a sub folder in the themes folder
     | containing a view, model (optional) and controller (optional).
     |
     */
    'theme' => [
        'class' => PHPageBuilder\Theme::class,
        'folder' => __DIR__ . '/themes',
        'folder_url' => '/themes',
        'active_theme' => 'demo'
    ],

    /*
     |--------------------------------------------------------------------------
     | Routing settings
     |--------------------------------------------------------------------------
     |
     | Settings for resolving pages based on the current URI.
     |
     */
    'router' => [
        'class' => PHPageBuilder\Modules\Router\DatabasePageRouter::class
    ],

    /*
     |--------------------------------------------------------------------------
     | Class replacements
     |--------------------------------------------------------------------------
     |
     | Allows mapping a class namespace to an alternative namespace,
     | useful for replacing implementations of specific pagebuilder classes.
     | Example: PHPageBuilder\UploadedFile::class => Alternative\UploadedFile::class
     | Important: when overriding a class always extend the original class.
     |
     */
    'class_replacements' => [
    ],
];

```

Here i used var_dump to get the variables in `phpb_current_full_url()`:

```
string(18) "protocol_variable:" string(4) "http" 
string(17) "currentFullUrl_1:" string(24) "http://test.e-hilfe.com/"
 string(17) "currentFullUrl_2:" string(23) "http://test.e-hilfe.com" 
```

**Comment by parmando** [comment]
I installed on other servers and the result was the same, I think this works only on the developer server kkkkkkkkkk

**Comment by HansSchouten** [comment]
@leonp5 In your output I am missing half of the config file. In this line it states the base_url: https://github.com/HansSchouten/PHPageBuilder/blob/master/config/config.example.php#L13

**Comment by parmando** [comment]
My config looks like this:

`<?php

return [
    /*
     |--------------------------------------------------------------------------
     | General settings
     |--------------------------------------------------------------------------
     |
     | General settings for configuring the PageBuilder.
     |
     */
    'general' => [
        'base_url' => 'https://otimo.site',
        'language' => 'en',
        'assets_url' => '/assets',
        'uploads_url' => '/uploads'
    ],

    /*
     |--------------------------------------------------------------------------
     | Storage settings
     |--------------------------------------------------------------------------
     |
     | Database and file storage settings.
     |
     */
    'storage' => [
        'use_database' => true,
        'database' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'otimo_xxx',
            'username'  => 'otimo_xxx',
            'password'  => 'xxx',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
        'uploads_folder' => __DIR__ . '/uploads'
    ],

    /*
     |--------------------------------------------------------------------------
     | Auth settings
     |--------------------------------------------------------------------------
     |
     | By default an authentication class is provided which checks for the
     | credentials configured in this setting block.
     |
     */
    'auth' => [
        'use_login' => true,
        'class' => PHPageBuilder\Modules\Auth\Auth::class,
        'url' => '/admin/auth',
        'username' => 'admin',
        'password' => 'changethispassword'
    ],

    /*
     |--------------------------------------------------------------------------
     | WebsiteManager settings
     |--------------------------------------------------------------------------
     |
     | By default a basic WebsiteManager is provided for creating/editing pages.
     |
     */
    'website_manager' => [
        'use_website_manager' => true,
        'class' => PHPageBuilder\Modules\WebsiteManager\WebsiteManager::class,
        'url' => '/admin'
    ],

    /*
     |--------------------------------------------------------------------------
     | Website settings
     |--------------------------------------------------------------------------
     |
     | By default a setting class is provided for accessing website settings.
     |
     */
    'setting' => [
        'class' => PHPageBuilder\Setting::class
    ],

    /*
     |--------------------------------------------------------------------------
     | PageBuilder settings
     |--------------------------------------------------------------------------
     |
     | By default a PageBuilder is provided based on GrapesJS.
     |
     */
    'pagebuilder' => [
        'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
        'url' => '/admin/pagebuilder',
        'actions' => [
            'back' => '/admin'
        ]
    ],

    /*
     |--------------------------------------------------------------------------
     | Page settings
     |--------------------------------------------------------------------------
     |
     | By default a Page class is provided with knowledge about its layout and URL.
     |
     */
    'page' => [
        'class' => PHPageBuilder\Page::class,
        'table' => 'pages',
        'translation' => [
            'class' => PHPageBuilder\PageTranslation::class,
            'table' => 'page_translations',
            'foreign_key' => 'page_id',
        ]
    ],

    /*
     |--------------------------------------------------------------------------
     | Theme settings
     |--------------------------------------------------------------------------
     |
     | PageBuilder requires a themes folder in which for each theme the individual
     | theme blocks are defined. A theme block is a sub folder in the themes folder
     | containing a view, model (optional) and controller (optional).
     |
     */
    'theme' => [
        'class' => PHPageBuilder\Theme::class,
        'folder' => __DIR__ . '/themes',
        'folder_url' => '/themes',
        'active_theme' => 'demo'
    ],

    /*
     |--------------------------------------------------------------------------
     | Routing settings
     |--------------------------------------------------------------------------
     |
     | Settings for resolving pages based on the current URI.
     |
     */
    'router' => [
        'class' => PHPageBuilder\Modules\Router\DatabasePageRouter::class
    ],

    /*
     |--------------------------------------------------------------------------
     | Class replacements
     |--------------------------------------------------------------------------
     |
     | Allows mapping a class namespace to an alternative namespace,
     | useful for replacing implementations of specific pagebuilder classes.
     | Example: PHPageBuilder\UploadedFile::class => Alternative\UploadedFile::class
     | Important: when overriding a class always extend the original class.
     |
     */
    'class_replacements' => [
    ],
];
`

**Comment by HansSchouten** [comment]
Can you try the `https://www.otimo.site/` `base_url`. You don't have the `www` in your `base_url`

**Comment by HansSchouten** [comment]
If you don't want `www` you can comment some lines in the .htaccess file

**Comment by parmando** [comment]
**Perfect! Problem solved, thank you!**
https://www.otimo.site/admin

**Comment by HansSchouten** [comment]
Great! You're welcome. I will keep this in mind and make it more resilient.

**Comment by leonp5** [comment]
@HansSchouten yes, sorry. I don't use nano often so i didn't realize that there was something missing when i copied it from the server.

So here is the start of the config:

```
<?php

return [
    /*
     |--------------------------------------------------------------------------
     | General settings
     |--------------------------------------------------------------------------
     |
     | General settings for configuring the PageBuilder.
     |
     */
    'general' => [
        'base_url' => 'http://localhost',
        'language' => 'en',
        'assets_url' => '/assets',
        'uploads_url' => '/uploads'
    ],

```

I changed 'base_url' to `'base_url' => 'http://test.e-hilfe.com/'` and now it works too here :) Thanks!

**Comment by HansSchouten** [comment]
Awesome, glad to hear that!
