### ISSUE TITLE
Configure settings for a block

### ISSUE THREAD

**Issue by chuajose** [HansSchouten/PHPageBuilder#31]
I am trying to create a block to manage sliders.https: //getbootstrap.com/docs/4.0/components/carousel/
How could I configure the settings of this block so that when selecting the block it allows me to indicate how many images and their urls. Right now if I define 3 images in the block, it allows me to change the image by clicking on each one ...
Could you use a file such as config.php to indicate what settings will this block allow?

**Comment by HansSchouten** [comment]
Here you can see the supported types: https://github.com/HansSchouten/PHPageBuilder/blob/bd1cd30ad28320fc2b8cc4a3ae5ba97cfb090891/src/Modules/GrapesJS/Block/BlockAdapter.php#L113. At the moment upload from the sidebar is not yet possible. So at the moment you should add a text type with the urls comma separated, or read the images from some other source than a block setting.

**Comment by chuajose** [comment]
185/5000
Thank you very much for the reply.

Then could I add a form on the settings page with that data? for example the urls of the images? How could I generate that form?

**Comment by chuajose** [comment]
`return [
    'label' => 'Separador',
    'category' => 'General',
    'icon' => 'fa fa-hand-peace-o',
    'settings' => [
        'height' => [
            'label'=> 'Height',
            'type' => 'text',
            'placeholder' =>'auto',
            'value' => 50
        ]
    ]
];
`

And call on view 

`<?php echo $block->setting('height');?>`

Thanks

**Comment by HansSchouten** [comment]
The setting value is returned here: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/Block/BaseModel.php#L66
In this method you can add some debug output to see why it always returns 50.
Do you see your value stored correctly in the database?

**Comment by chuajose** [comment]
sorry
It is working.
Thank you

**Comment by HansSchouten** [comment]
Thanks, great to hear that.

**Comment by mealyus** [comment]
> ```
> return [
>     'label' => 'Separador',
>     'category' => 'General',
>     'icon' => 'fa fa-hand-peace-o',
>     'settings' => [
>         'height' => [
>             'label'=> 'Height',
>             'type' => 'text',
>             'placeholder' =>'auto',
>             'value' => 50
>         ]
>     ]
> ];
> ```
> 
> And call on view
> 
> ```
> echo $block->setting('height');
> ```
> 
> On the edit page, I change the height value and apply it correctly and store it, but on the web view page, it keeps the default value

Hi, What if we have to add a custom image as a thumbnail in the icon section?
