### ISSUE TITLE
Add SEO tags to pages

### ISSUE THREAD

**Issue by parmando** [HansSchouten/PHPageBuilder#32]
How can I edit page data such as Title, meta tags, description and other tags before </head>?
Is it possible to do this for any block?

**Comment by HansSchouten** [comment]
This information is page specific and not really depending on the blocks. So I would add it to the layout files you are using.
For instance this can be added to a layout file to add a page title:
```
<title><?= $page->getTranslation('title') ?></title>
```

At the moment the included website manager does not support setting a meta description (I don't use the website manager myself but integrated PHPageBuilder in a Laravel project that manages the page info etc).
However, you can do this similarly as the page title, by adding additional fields to the `page_translations` table and outputting them into your layout by using `<?= $page->getTranslation('meta_description') ?>`.
