### ISSUE TITLE
"composer require hansschouten/phpagebuilder" brokes laravel project

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#33]
tested on laravel 6

1. composer require hansschouten/phpagebuilder succesfully installs phpagebuilder

2. open any page containing CSRF token

this code in blade template
`{{ csrf_field() }}`

produces  
`&lt;input type=&quot;hidden&quot; name=&quot;_token&quot; value=&quot;BGWtUp7p7lY6fJQMlAAT2vRhlWc0PvVC3vCL7o9j&quot;&gt;`

removing hansschouten/phpagebuilder fixes CSRF double encoding

bad thing that the phppagebuilder library brokes CSRF whenever not used anywhere in laravel, just added via composer

**Comment by HansSchouten** [comment]
That is not good indeed, thanks for pointing out. Could you try removing this method: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Core/helpers.php#L11 and see if that is the cause?

**Comment by dsultanr** [comment]
yes, removing this method helps

Do you think moving helpers to custom namespace is a good way?

**Comment by HansSchouten** [comment]
Thanks for checking, good to know. Creating a class that provides the helper functions could be a solution. Although putting `namespace\Helper::method()` at many locations in for example view files makes the code a less readable. An alternative would be prefixing all helpers with `phpb_` that I already did with a number of methods.

**Comment by dsultanr** [comment]
could you please make a quick fix for this method only?

пн, 9 нояб. 2020 г., 23:41 Hans Schouten <notifications@github.com>:

**Comment by HansSchouten** [comment]
No problem, I just published the v0.14.0 release (https://github.com/HansSchouten/PHPageBuilder/releases/tag/v0.14.0) that fixes this issue.

**Comment by dsultanr** [comment]
fixed. thanks
