### ISSUE TITLE
multi-user functionality

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#34]
Hi Hans!

Need your advice

My goal is to add your builder functionality independently to all of my users on my current laravel project

My thoughts was to add an extra column user_id into pages table

Which class will be easier to extend/replace to implement multi-user functionality?

**Comment by HansSchouten** [comment]
I don't think you need to replace that much. It is no problem to add a custom user_id column to the pages table.
Next you should use a Laravel controller method that calls the pagebuilder to edit a given page. This controller method should check whether the current user has permissions to edit that page.
To do this see this thread (and other issues in that repo): https://github.com/HansSchouten/Laravel-Pagebuilder/issues/8
