### ISSUE TITLE
styles and scripts are lost

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#38]
here is my block's content 

```
<style type="text/css">
    #bac-carousel-wrapper {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-inedx: -1;
    }
    .bac-carousel-item {
        background: center center/cover no-repeat;
        z-index: 0;
        width: 100%;
        height: 100%;
        position: absolute;
        -webkit-transition: 1.3s opacity;
        transition: 1.3s opacity;
        opacity: 0;
    }

    .bac-carousel-item.active {
        opacity: 1;
    }
</style>


<div id="bac-carousel-wrapper">
    <div class="bac-carousel-item active" style="background-image: url('/images/slide-bg1.jpg');"></div>
    <div class="bac-carousel-item" style="background-image: url('/images/slide-bg2.jpg');"></div>
    <div class="bac-carousel-item" style="background-image: url('/images/slide-bg3.jpg');"></div>
</div>

<script type="text/javascript">
    try {
        const bacCarouselItems = document.querySelectorAll(".bac-carousel-item");
        let itemNum = 1;
        setInterval(() =>{
            if(itemNum == bacCarouselItems.length) {
                itemNum = 0;
                bacCarouselItems.forEach(item => item === bacCarouselItems[itemNum] ? bacCarouselItems[itemNum].classList.add("active") : item.classList.remove("active"));
                itemNum = 1;
            } else {
                bacCarouselItems.forEach(item => item === bacCarouselItems[itemNum] ? bacCarouselItems[itemNum].classList.add("active") : item.classList.remove("active"));
                itemNum++;
            }
        }, 10000);
    } catch {}
</script>

```
Seems my scripts are removed from blocks on save. 
Is that neccesary? I need custom script for some blocks, how should I add them correctly to block?

Also GrapesJS moved my inline styles to external style but neither new IDs nor classes are not used
```

<div id="bac-carousel-wrapper" class="IDKHLQN54ECOJFT1">
    <div class="bac-carousel-item active IDKHLQN54PVQJPB2"></div>
    <div class="bac-carousel-item IDKHLQN54TE7U8Q3"></div>
    <div class="bac-carousel-item IDKHLQN54WJ6MQX4"></div>
<style>
    #ieeou{background-image:url('/images/slide-bg1.jpg');}
    #izso2{background-image:url('/images/slide-bg2.jpg');}
    #ijyki{background-image:url('/images/slide-bg3.jpg')
</style>



```

**Comment by dsultanr** [comment]
I found  
`'avoidInlineStyle' => true,`
in src/Modules/GrapesJS/resources/views/grapesjs/config.php
is that setting cause of style loosing? what gonna happen if I turn it to false?

Seems my scripts are also removed from blocks on building. Is that neccesary? I need custom script for some blocks, how should I add them correctly?

**Comment by HansSchouten** [comment]
I see scripts are indeed removed on save. This might be something that GrapesJS is doing in the background, but I am not yet sure. Anyway, you can create a `script.js` file in your block folder and this should work just fine.

**Comment by dsultanr** [comment]
> I see scripts are indeed removed on save. This might be something that GrapesJS is doing in the background, but I am not yet sure. Anyway, you can create a `script.js` file in your block folder and this should work just fine.

Yes, script.js inside a block's folder did the trick

Regarding styles - I did patch `vendor/hansschouten/phpagebuilder/src/Modules/GrapesJS/resources/views/grapesjs/config.php` 

`'avoidInlineStyle' => true,`
to
`    'avoidInlineStyle' => false,
`

and inline styles began to work. Could you please add this option to phpb_config?

**Comment by dsultanr** [comment]
Just noticed - `<styles>` block also lost

is `style.css` will work in my block folder as a `script.js` you mentioned before?

**Comment by dsultanr** [comment]
> I see scripts are indeed removed on save. This might be something that GrapesJS is doing in the background, but I am not yet sure. Anyway, you can create a `script.js` file in your block folder and this should work just fine.

script.js inside the block embedded in public as this code

```
<script type="text/javascript" class="script2595779758">
document.getElementsByClassName("script2595779758")[0].addEventListener("run-script", function() {
	let inPageBuilder = false;
	let block = document.getElementsByClassName("script2595779758")[0].previousSibling;
	let blockSelector = "." + block.className;
		try {
		    const bacCarouselItems = document.querySelectorAll(".bac-carousel-item");
		    let itemNum = 1;
		    setInterval(() =>{
		        if(itemNum == bacCarouselItems.length) {
		            itemNum = 0;
		            bacCarouselItems.forEach(item => item === bacCarouselItems[itemNum] ? bacCarouselItems[itemNum].classList.add("active") : item.classList.remove("active"));
		            itemNum = 1;
		        } else {
		            bacCarouselItems.forEach(item => item === bacCarouselItems[itemNum] ? bacCarouselItems[itemNum].classList.add("active") : item.classList.remove("active"));
		            itemNum++;
		        }
		    }, 10000);
		} catch {}
	});
</script>
```

but `run-script` never fired

any thoughts?

**Comment by dsultanr** [comment]
I did some patching again and it works

https://github.com/HansSchouten/PHPageBuilder/src/Modules/GrapesJS/Block/BlockRenderer.php#L163-L175

```
    protected function wrapScriptWithScopeAndContextData($script)
    {
        $scriptId = 'script' . rand(0, 10000000000);
        $html = '<script type="text/javascript" class="' . $scriptId . '">'. PHP_EOL;
        $html .= 'let inPageBuilder = false;'. PHP_EOL;
        $html .= 'let block = document.getElementsByClassName("' . $scriptId . '")[0].previousSibling;'. PHP_EOL;
        $html .= 'let blockSelector = "." + block.className;'. PHP_EOL;
        $html .= 'var items = document.querySelectorAll(blockSelector);';
        $html .= '  for (var i = 0, len = items.length; i < len; i++) {';
        $html .= '    (function(){';
        $html .= '      // START component code'. PHP_EOL;
        $html .= $script;
        $html .= '      // END component code'. PHP_EOL;
        $html .= '    }.bind(items[i]))();';
        $html .= '  }';
        $html .= '</script>';
        return $html;
    }
```
samle code for running block's scripts got from here: https://grapesjs.com/docs/modules/Components-js.html#basic-scripts

**Comment by HansSchouten** [comment]
The run scripts is fired if you add this to the very bottom of your layout files:
```
<script type="text/javascript">
    document.querySelectorAll("script").forEach(function(scriptTag) {
        scriptTag.dispatchEvent(new Event('run-script'));
    });
</script>
```

**Comment by HansSchouten** [comment]
The problem with the other approach is, like mentiond in GrapesJS:

> Keep in mind that all component scripts are executed only inside the iframe of the canvas (isolated, just like your final template), and therefore are NOT part of the current document. All your external libraries (eg. jQuery) are not there, but you'll see later how to manage scripted components with dependencies.

You don't have access to the scripts loaded at the end of your page body. By triggering these events, you do have access to them.

**Comment by dsultanr** [comment]
I had no idea yesterday about why run-script is missing. That's why I made this workaround. Thank you for keep in touch :)

One more edge case - I need the script to be inserted inside concrete div tag... How about this?

**Comment by dsultanr** [comment]
> I need the script to be inserted inside concrete div tag

Done this by custom script.js

```
    var script = document.createElement("script");
    var done = false;
    script.src = 'https://external.js';
    document.getElementsByClassName("address-map")[0].appendChild(script);    

```

**Comment by HansSchouten** [comment]
Ok, you are right. I should add that snippet to the readme or at least the [boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate). Yes, you can add the script in specific locations that way. So everything is working now?

**Comment by dsultanr** [comment]
yep. thanks :)

**Comment by dsultanr** [comment]
> Regarding styles - I did patch `vendor/hansschouten/phpagebuilder/src/Modules/GrapesJS/resources/views/grapesjs/config.php`
> 
> `'avoidInlineStyle' => true,`
> to
> ` 'avoidInlineStyle' => false,`
> 
> and inline styles began to work. Could you please add this option to phpb_config? Or any other solution?

this issue is left out of the discussion scope. consider please

**Comment by HansSchouten** [comment]
You are right. However, I was using that setting before but it gave all kinds of issues with saving styles. This setting saves all inline styles, but consider what happens if you are using an image slider or other blocks with advanced JS. These plugins will add all kinds of style and this all would be saved. And there were more issues as well.

**Comment by dsultanr** [comment]
moreover I have seen somewhere on GrapesJS's github that this option will be forced to true in future releases

**Comment by HansSchouten** [comment]
Ok, thanks for the heads up. Once they would build websites as complex as [my customers](https://www.happy-vakantiehuis.nl/vakantiehuis-zoeken) while still offering very easy component script notations. Inline styling would definitely break when saving pages. Or scripts should be disabled in the pagebuilder, but that makes editing html inside tab components [like here](https://www.villaguapaspain.com/en/the-villa) impossible.
