### ISSUE TITLE
Class 'PHPageBuilder' not found!!!

### ISSUE THREAD

**Issue by dev-shack** [HansSchouten/PHPageBuilder#39]
Hey!! First, this is an amazing package, but I am unable to integrate it into my existing project, it is giving me an error when I am creating my controller and I don't know what is causing this error!! Please can you guide me on what is causing this?

**Comment by HansSchouten** [comment]
Are you using the [Laravel package](https://github.com/HansSchouten/Laravel-Pagebuilder)? If not, please have a look at [the boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate). Maybe this line is not added or working properly:
```
require_once __DIR__ . '/vendor/autoload.php';
```
Or this snippet if you don't use composer:
```
$installationFolder = __DIR__ . '/phpagebuilder';
require_once $installationFolder . '/src/Core/helpers.php';
spl_autoload_register('phpb_autoload');
```

**Comment by dev-shack** [comment]
Hey! Thanks for the quick response,. Yes, I am using laravel package.
Yes, this line exists in my index.php file,
![image](https://user-images.githubusercontent.com/72554123/99656574-e1f35a80-2a7e-11eb-9af9-14215cad2add.png)

What should I do with this line to successfully run the page builder and to remove this issue?

Thanks again!

**Comment by dev-shack** [comment]
And one more thing, what should I add up in AppServiceProvider so, It should pick the class, please check the image below!
![image](https://user-images.githubusercontent.com/72554123/99657332-da808100-2a7f-11eb-90b4-76c91553d7b6.png)

**Comment by HansSchouten** [comment]
If you use the Laravel package you don't need to alter the AppServiceProvider, as that is done by the package [here](https://github.com/HansSchouten/Laravel-Pagebuilder/blob/master/src/ServiceProvider.php).

**Comment by dev-shack** [comment]
![image](https://user-images.githubusercontent.com/72554123/99660280-f71eb800-2a83-11eb-9833-390ae6e3b947.png)
When I run composer dump-autoload, it gives me this error, and below is my index.php file
![image](https://user-images.githubusercontent.com/72554123/99660545-4fee5080-2a84-11eb-8acb-2bb36bae4443.png)

**Comment by dev-shack** [comment]
Now I am removing the package and re-installing it again, what steps should I do? Because migrations are all there and **themes** folder is also there!, I have the controller and the model too!

**Comment by dev-shack** [comment]
This what I am getting after reinstalling the package! 😢😢
![image](https://user-images.githubusercontent.com/72554123/99661473-af009500-2a85-11eb-97da-79a9796782a9.png)

**Comment by HansSchouten** [comment]
Can you share the contents of `/config/pagebuilder.php`?

**Comment by dev-shack** [comment]
I think it works when I have removed the package, deleted the /config/pagebuilder.php file, and again install the package and now it does not show me any error!

**Comment by dev-shack** [comment]
But I am testing it, once I got it up and running, I will close the issue, and again thanks a lot for the prompt response! Much Appreciated!

**Comment by dev-shack** [comment]
**Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()**, 
this is what I am getting when accessing http://goodvibes.test/admin/pages/1/build

**Comment by dev-shack** [comment]
Thanks man! It is up and running!
