### ISSUE TITLE
block content is not editable

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#40]
I have a block with content

```
<div class="wrapper address-wrapper">
    <div class="address-item">
        <div class="address-item-title">City</div>
```

"City" word is not editable inside pagebuilder. Should I wrap it with some tag? which one?

**Comment by HansSchouten** [comment]
Hi that is correct, these are at the moment the only supported editable tags: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/assets/js/manage-editable-components.js#L686

**Comment by dsultanr** [comment]
https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/Block/BlockRenderer.php#L686-L694

**Comment by dsultanr** [comment]
@HansSchouten is it possible to let users to change backround image? for example in sliders. what approach should I use to achieve this?

**Comment by HansSchouten** [comment]
Changing fontawesome icons is a good one, I still need to add that. Background images can already be changed via de styling tab in the sidebar.

**Comment by dsultanr** [comment]
May I contribute with FA icons somehow? Any ideas how to implement this?

**Comment by HansSchouten** [comment]
Yes feel free to add improvements. Actually I don't know yet what would be the best option. I guess a similar popup to the image selector (which I am planning to replace by something more beautiful as well). Or as an alternative add an icon selector setting to the sidebar. If I am correct GrapesJS itself already had a solution for selecting icons somewhere.
