### ISSUE TITLE
Problem with laravel 8 i think

### ISSUE THREAD

**Issue by mariojgt** [HansSchouten/PHPageBuilder#41]
Hi there i jsut isntall your package with a fresh laravel 8 and i did all the setup steps but for some reason i keep geting a page not found when i access the /admin there is any i can render that page just caling a view or a class, Thanks.

**Comment by HansSchouten** [comment]
Hi could you double check the contents of your config file. Especially the `base_url` should 100% match with the URL of your project's homepage, including http or https and any subdomain or subfolder.
