### ISSUE TITLE
app.js:formatted:425 Uncaught TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#43]
![image](https://user-images.githubusercontent.com/1683476/100210758-6715be00-2f1c-11eb-9475-51c38a023585.png)

**Comment by HansSchouten** [comment]
When does this error exactly occur? I haven't seen this one yet, while using the package daily.

**Comment by dsultanr** [comment]
this happens when I do insert a very complex view.php block with many styles and scripts. It's a whole site's page actually but I want it to be a block

what is your advice on integrating such a blocks?

![image](https://user-images.githubusercontent.com/1683476/100318423-101cf100-2fcf-11eb-8e82-40ee50bb5b9b.png)

**Comment by HansSchouten** [comment]
I would create a layout file that contains all the meta, link and script tags (see [this example](https://github.com/HansSchouten/PHPagebuilder-boilerplate/blob/master/themes/demo/layouts/master/view.php)). Next I would put the javascript inside a file called `script.js` in the folder of the block. Then you can create a page that uses your layout file and then drag the block of this entire page onto it.

**Comment by dsultanr** [comment]
> create a page that uses your layout

what does it mean? create a block?

**Comment by HansSchouten** [comment]
No, it means to create a folder like this one: https://github.com/HansSchouten/PHPagebuilder-boilerplate/tree/master/themes/demo/layouts
