### ISSUE TITLE
 Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by santoshmohan04** [HansSchouten/PHPageBuilder#44]
( ! ) Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'android.angular_page_translations' doesn't exist in C:\wamp64\www\AngularJs\src\Core\DB.php on line 64
--
I am struck here 

![image](https://user-images.githubusercontent.com/66831164/100263251-46c51e00-2f73-11eb-84ae-d14889610caa.png)

**Comment by HansSchouten** [comment]
Did you run: https://github.com/HansSchouten/PHPageBuilder/blob/master/config/create-tables.sql?

**Comment by santoshmohan04** [comment]
> Did you run: https://github.com/HansSchouten/PHPageBuilder/blob/master/config/create-tables.sql?
> 
> Edit: I see it is looking for the table `angular_page_translations`, so you have configured the prefix `angular` in your phpagebuilder config file. However, the tables are probably not created with this prefix.

I renamed the tables with angular prefix, the error has gone but after clicking  "get started" it is navigating to "/admin" which is not there in my folder.
how to deal with it?
![image](https://user-images.githubusercontent.com/66831164/100310358-02696a80-2fd3-11eb-97c8-84772f0af315.png)
![image](https://user-images.githubusercontent.com/66831164/100310382-144b0d80-2fd3-11eb-8325-732dfc8d6431.png)

**Comment by HansSchouten** [comment]
All requests starting with `localhost/AngularJs` are pointed to `index.php` via your `.htaccess` (probably from the [boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate)). So you don't need an admin folder, the `index.php` file is ran for each URL, it loads the pagebuilder package and will look at the current URL and output the necessary page html.

However, to correctly interpret the current URL it needs to know at which URL the package is installed. So please make sure you have `http://localhost/AnglularJs` configured as `base_url` in your pagebuilder config file.

**Comment by santoshmohan04** [comment]
> All requests starting with `localhost/AngularJs` are pointed to `index.php` via your `.htaccess` (probably from the [boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate/blob/master/.htaccess#L33)). So you don't need an admin folder, the `index.php` file is ran for each URL, it loads the pagebuilder package and will look at the current URL and output the necessary page html.
> 
> However, to correctly interpret the current URL it needs to know at which URL the package is installed. So please make sure you have `http://localhost/AnglularJs` configured as `base_url` in your pagebuilder config file.

I followed all the steps mentioned in https://github.com/HansSchouten/PHPageBuilder and place them in a project folder but could not see page builder while navigating to http://localhost/Angularjs/ where I went wrong.
![image](https://user-images.githubusercontent.com/66831164/100321533-d658e400-2fe8-11eb-9bfe-473741c929b8.png)
![image](https://user-images.githubusercontent.com/66831164/100321813-4a938780-2fe9-11eb-875e-117c8952b996.png)
![image](https://user-images.githubusercontent.com/66831164/100321850-58e1a380-2fe9-11eb-9bb2-a2f35d6391cb.png)
![image](https://user-images.githubusercontent.com/66831164/100321886-66972900-2fe9-11eb-9c8b-dee43cb499e8.png)
![image](https://user-images.githubusercontent.com/66831164/100321927-757ddb80-2fe9-11eb-96cc-c4ee7885ec23.png)
![image](https://user-images.githubusercontent.com/66831164/100321976-8e868c80-2fe9-11eb-8884-c84676a6fd7c.png)

**Comment by HansSchouten** [comment]
What is your value of the `base_url` setting in the pagebuilder config file?

**Comment by santoshmohan04** [comment]
> What is your value of the `base_url` setting in the pagebuilder config file? You should have set it to `http://localhost/AnglularJs`.

Yes my 'base_url' is the same 
![image](https://user-images.githubusercontent.com/66831164/100362667-bb569600-3021-11eb-8133-63b3e300992a.png)

**Comment by HansSchouten** [comment]
Ok great, so that is correct. With one more look on your folder screenshot I see there is no .htaccess file. This is most likely the issue. Please add [this file](https://github.com/HansSchouten/PHPagebuilder-boilerplate/blob/master/.htaccess).

**Comment by santoshmohan04** [comment]
> Ok great, so that is correct. With one more look on your folder screenshot I see there is no .htaccess file. This is most likely the issue. Please add [this file](https://github.com/HansSchouten/PHPagebuilder-boilerplate/blob/master/.htaccess).

When I am trying to reach http://localhost/AngularJS  it is redirecting to www.localhost
![image](https://user-images.githubusercontent.com/66831164/100429889-06bd8280-30bc-11eb-830e-b5b1acf84652.png)

**Comment by HansSchouten** [comment]
Ah that is correct, in the .htaccess file there is a line that performs this redirect. You can remove it if you want to

**Comment by santoshmohan04** [comment]
> Ah that is correct, in the .htaccess file there is a line that performs this redirect. You can remove it if you want to

can you specify which line has to be removed,  this is the .htaccess file contents:
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Redirect non-www. to www. (except when on a subdomain)
    RewriteCond %{HTTP_HOST} !^www\.
    RewriteCond %{HTTP_HOST} !^(.*)\.(.*)\. [NC]
    RewriteRule ^ https://www.%{HTTP_HOST}/$1 [R=301,L]

    # Redirect HTTP to HTTPS
    RewriteCond %{HTTPS} !=on
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

    # Remove any trailing slashes from non-directories using a redirect
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [R=301,L]

    # Rewrite /themes/{theme}/{file} to /themes/{theme}/public/{file}
    RewriteRule ^themes/([^/]+)/(?!public/)(.*)$ themes/$1/public/$2 [L]

    # Rewrite non-directory and non-file URLs to index.php
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Allow direct access to theme files with URL format: /themes/{theme}/public/{file}
    RewriteRule ^themes/([^/]+)/public/(.*)$ themes/$1/public/$2 [L]

    # Allow direct access to uploaded files with URL format: /uploads/{filepath;,}
    RewriteRule ^uploads/(.*)$ uploads/$1 [L]

    # Rewrite all remaining requests to index.php
    RewriteRule ^ index.php [L]
</IfModule>

**Comment by HansSchouten** [comment]
The three lines below: `# Redirect non-www. to www. (except when on a subdomain)`.
