### ISSUE TITLE
Using Blade Templates and Adding Menu

### ISSUE THREAD

**Issue by macgadger** [HansSchouten/PHPageBuilder#45]
Hi Really like your work somthing i was looking for!!
But can you please tell me how i can use Blade Templates or How can i render Modules in Blade Views  and How to add Custome Menu ? Is it supported yet ? If Yes can you please explain how can i do it?

**Comment by HansSchouten** [comment]
Hi, glad to hear that! I am planning to add support for blade templates to the [Laravel Pagebuilder](https://github.com/HansSchouten/Laravel-Pagebuilder), but this is currently not supported unfortunately. I will soon work on that.

If you are using Laravel you can create controllers/views to create your own menu in your backend. Then in a php block you can read this from database and render the menu.
