### ISSUE TITLE
Integrating in php projects

### ISSUE THREAD

**Issue by luison** [HansSchouten/PHPageBuilder#48]
Great project. I was wondering if there are any instructions or tips about how to integrate into a php project (not laravel) in such a way that one could isolate the editor to the content area. This is... include a fixed pre-code and post-code after the builder so one could see it integrated within the project styles and only be editing main content area.
Thanks.

**Comment by HansSchouten** [comment]
Hi thanks, yes that is possible by using layouts if I understand your use-case correctly. You could create a layout like [here](https://github.com/HansSchouten/PHPagebuilder-boilerplate/tree/master/themes/demo/layouts/master) with all your default html and then within the layout paste the `<?= $body ?>` at the location that should be editable.
