### ISSUE TITLE
Cache issue "Call to a member function invalidate() on null "

### ISSUE THREAD

**Issue by Dontorpedo** [HansSchouten/PHPageBuilder#52]
i have updated to 0.18.0 and was not able to save changes.. error is:

Call to a member function invalidate() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function invalidate() on null at /home/ploi/mypage/vendor/hansschouten/phpagebuilder/src/Page.php:177) 

after uncommenting this line it worked again.

**Comment by HansSchouten** [comment]
You should update your config file, to add [this segment](https://github.com/HansSchouten/PHPageBuilder/blob/master/config/config.example.php#L130).

**Comment by Dontorpedo** [comment]
oh, ok.. thank your.. it works now.
