### ISSUE TITLE
Struggle on installation

### ISSUE THREAD

**Issue by meriemjd** [HansSchouten/PHPageBuilder#54]
Hi, 

I have a problem in the configuration file, I can't understand how to set the base_url in the config file.
Should I put http://mydomainname.com or I did it wrong, because Whenever I want to access http://mydomainname.com/name_of_folder_where_i_did_put_all_the_structure_of_phpagebuilder, I have this error : **PHPageBuilder page not found. Check your URL**

Please, can you give me some help,

Thank's in advance.

**Comment by HansSchouten** [comment]
Yes that should be your `base_url`. However it should also include `www.` if you are using that (I think this is the default of the [pagebuilder boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate) code).
