### ISSUE TITLE
Adding images to blocks panel instead of icons

### ISSUE THREAD

**Issue by ryguy2407** [HansSchouten/PHPageBuilder#55]
Thanks for this package, so far it looks great. I just can't figure out how to get image thumbnails on my blocks instead of icons? Images like the ones that you have in your example screenshot.
![Screen Shot 2021-02-03 at 9 47 45 am](https://user-images.githubusercontent.com/5257196/106677672-e6063180-6604-11eb-8f87-c0bac583b358.png)

**Comment by HansSchouten** [comment]
Hi thanks, please have a look over here: https://github.com/HansSchouten/PHPageBuilder/issues/5
