### ISSUE TITLE
Class 'PHPageBuilder\PHPageBuilder' not found

### ISSUE THREAD

**Issue by milan-atulyam** [HansSchouten/PHPageBuilder#58]
Hello Team,

While i am integrating this plugin getting error Class 'PHPageBuilder\PHPageBuilder' not found and also getting 

Class 'PHPageBuilder\Repositories\PageRepository' not found

![image](https://user-images.githubusercontent.com/78948340/110745503-5ede5600-8261-11eb-90a0-678fd028e9c0.png)

![image](https://user-images.githubusercontent.com/78948340/110745538-6c93db80-8261-11eb-89e0-fdee2bad224b.png)

![image](https://user-images.githubusercontent.com/78948340/110745581-79b0ca80-8261-11eb-83b2-c7e773ddb7c2.png)

![image](https://user-images.githubusercontent.com/78948340/110745678-a49b1e80-8261-11eb-8ffb-1d3a482403a6.png)

Included both the classes in controller and appserviceprovider but then also it populate errors.

**Comment by HansSchouten** [comment]
Strange, never had that before. Are you sure you have `hansschouten/phpagebuilder` in your composer.json and lock files?
