### ISSUE TITLE
Theming: Renaming a block from .html to .php changes the look / HTML structure

### ISSUE THREAD

**Issue by amenk** [HansSchouten/PHPageBuilder#64]
I am trying to convert the [startbootstrap creative theme](https://startbootstrap.com/theme/creative) to a PHPageBuilder theme.

For the portofolio section I want to be able to edit hyperlink and image.

As soon as I change the portofolio-box from .html to .php (https://github.com/AddisMap/phpb-startbootstrap-creative/blob/fee16f2d4e6592e8fd486debf56289c762e30845/blocks/portfolio-box/view.php) most styling is lost.

I believe this is due to the different HTML structure:

HTML template - as it should look

![structure-as-html-file](https://user-images.githubusercontent.com/1087128/114308096-f47c3800-9ae2-11eb-9186-c1b5e82f6c91.png)

PHP template - broken

![structure-as-php-file](https://user-images.githubusercontent.com/1087128/114308114-fe05a000-9ae2-11eb-86f5-3a57c53aebb0.png)

Is this intended?

**Comment by HansSchouten** [comment]
This is to add a wrapper which can receive the styling of a dynamic block. Otherwise it is not possible to add styling (margin, padding etc) using the pagebuilder sidebar. At the moment I don't see another way of achieving this.

**Comment by amenk** [comment]
Thank you
