### ISSUE TITLE
import multiple block instance to a single block

### ISSUE THREAD

**Issue by dumithsalinda** [HansSchouten/PHPageBuilder#68]
I was added the multiple blocks to a single block.

```
<section>
<div class=”column”>[block slug=”card”]</div>
<div class=”column”>[block slug=”card”]</div>
<div class=”column”>[block slug=”card”]</div>
</section>
```

but, When I try to set a different image per card (or text) it changes all cards to the same. 
Is there a way to fix this. 

Thank you

**Comment by HansSchouten** [comment]
Yes in that case you need to add an id attribute. So: `[block slug="card" id="card1"]`.

**Comment by dumithsalinda** [comment]
Thank you
