### ISSUE TITLE
cannot load sql script into mariadb

### ISSUE THREAD

**Issue by aermike** [HansSchouten/PHPageBuilder#7]
OS: CentOS7
db: Your MariaDB connection id is 11
Server version: 5.5.64-MariaDB MariaDB Server
Try to load mycreate-tables.sql into **web** database
 mysql -u user -p web < create-tables.sql
ERROR 1293 (HY000) at line 11: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

**Comment by HansSchouten** [comment]
Hi, I don't have a similar environment to check this out nor do I know a direct fix. I see your MariaDB version is almost EOL, so can you update it or maybe suggest a way to fix the query.

**Comment by aermike** [comment]
Tested on debian it works 
You have right. Mariadb server is problem

**Comment by aermike** [comment]
in mysql
create database name;
use database name;
set global innodb_large_prefix=on;
set global innodb_file_format=Barracuda;
set global innodb_default_row_format = DYNAMIC;
 After that in mysql load create-tables.sql
