### ISSUE TITLE
PHPageBuilder don't start

### ISSUE THREAD

**Issue by aermike** [HansSchouten/PHPageBuilder#9]
Hi
I use Debian GNU/Linux 9 , with MariaDB
Server version: 10.1.44-MariaDB-0+deb9u1 Debian 9.11
and PHP version 

php -v
PHP 7.4.5 (cli) (built: Apr 19 2020 08:42:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), b

When try to acces PHPageBuilder got this error

Warning: require_once(/var/www/html/PHPageBuilder/phpagebuilder/src/Core/helpers.php): failed to open stream: No such file or directory in /var/www/html/PHPageBuilder/index.php on line 10

Fatal error: require_once(): Failed opening required '/var/www/html/PHPageBuilder/phpagebuilder/src/Core/helpers.php' (include_path='.:/usr/share/php') in /var/www/html/PHPageBuilder/index.php on line 10

**Comment by HansSchouten** [comment]
So your website's root directory is called `PHPageBuilder`. In that directory you do have unzipped the latest release in a folder called `phpagebuilder`? Can you double check that the path `/var/www/html/PHPageBuilder/phpagebuilder/src/Core/helpers.php` exists. Unfortunately I cannot think of a reason why this require_once could fail.

**Comment by aermike** [comment]
Hi
My mistake
It was PHPageBuilder with all in 
Now modifyng with your instructions
Now appear "Page not found"
Image attach
![phpagebuilder](https://user-images.githubusercontent.com/4247309/80528760-1e565080-899f-11ea-93c5-241cb87d3338.PNG)

**Comment by HansSchouten** [comment]
That is because there is not yet a homepage created (with the route: `/`). You should be able to login via `/admin` and create a page. I agree the warning is still a bit vague, I will add a default welcome page soon.

**Comment by aermike** [comment]
Thank You
I do something wrong, and I don't know what
![phpagebuilder1](https://user-images.githubusercontent.com/4247309/80537110-2799ea00-89ac-11ea-83b8-ae2f20d33faf.PNG)

**Comment by HansSchouten** [comment]
The browser now requests the admin page in a folder called `index.php`. Index.php should never be part of any URL. Your URL should just be the instal directory followed by `/admin`.

**Comment by aermike** [comment]
![phpagebuilder2](https://user-images.githubusercontent.com/4247309/80589416-c9f4b480-8a22-11ea-9b5e-016cf0d8f90d.PNG)

**Comment by HansSchouten** [comment]
And `/PHPageBuilder` is still returning the correct "Page not found" message? If not, it only seems to work if you add `index.php` in the URL, which is not what we want. In that case it could be a `.htaccess` related problem.

**Comment by HansSchouten** [comment]
> ![phpagebuilder](https://user-images.githubusercontent.com/4247309/80528760-1e565080-899f-11ea-93c5-241cb87d3338.PNG)

Here it is already strange that `index.php` is in the URL.

**Comment by aermike** [comment]
Thanks for help
And /PHPageBuilder is still returning the correct "Page not found" message? 
Yes
And for 
http://ip/PHPageBuilder/admin have error with "Page Not found"
![phpagebuilder3](https://user-images.githubusercontent.com/4247309/80632662-3fcb4100-8a60-11ea-81f3-10414949fad4.PNG)
Any way, I don't see anything about 'admin' in this tree....maybe I was wrong (I don't know PHP, but if I have something like:
http://ip/PHPageBuilder/admin, I think maybe I need an folder named admin.
I don't see in git, to PHPageBuilder or biolerplate something about  admin

**Comment by aermike** [comment]
..and tree...:) sorry
![phpagebuilder4](https://user-images.githubusercontent.com/4247309/80633250-24146a80-8a61-11ea-8681-7e2b9a806264.PNG)

**Comment by aermike** [comment]
I was access index from this...
![phpagebuilder](https://user-images.githubusercontent.com/4247309/80633344-460ded00-8a61-11ea-9134-e48f8bcb6841.PNG)

**Comment by HansSchouten** [comment]
> ![phpagebuilder](https://user-images.githubusercontent.com/4247309/80528760-1e565080-899f-11ea-93c5-241cb87d3338.PNG)
Do you have the file `.htaccess`?

**Comment by aermike** [comment]
Yes 
Is unchanged from git
![phpagebuilder5](https://user-images.githubusercontent.com/4247309/80681874-31197400-8aca-11ea-82c8-378169f75875.PNG)

**Comment by HansSchouten** [comment]
I see it is not the latest version, I recently fixed a bug causing issues when using a subfolder (like you are using right now). The `RewriteBase / ` should be removed.

**Comment by aermike** [comment]
In latest version, I don't see any .htaccess
An error with appear again

When try to acces PHPageBuilder got this error

Warning: require_once(/var/www/html/PHPageBuilder/phpagebuilder/src/Core/helpers.php): failed to open stream: No such file or directory in /var/www/html/PHPageBuilder/index.php on line 10

Fatal error: require_once(): Failed opening required '/var/www/html/PHPageBuilder/phpagebuilder/src/Core/helpers.php' (include_path='.:/usr/share/php') in /var/www/html/PHPageBuilder/index.php on line 10



I have an vm, and an propeso to you if you are agree:
Take an snapshot and after that on clean install make step by step install , and you notice any steps and any erors with resolvation in some readme(I will help on that too)
And see if ends with and resultat
Are you agree?

**Comment by HansSchouten** [comment]
This is the `.htaccess` file I mean: https://github.com/HansSchouten/PHPagebuilder-boilerplate/blob/master/.htaccess.

Your project structure should be:
![afbeelding](https://user-images.githubusercontent.com/5946444/80694610-07197f00-8ad5-11ea-8286-d416c0aeebbc.png)

The downloaded version of PHPageBuilder should not be modified and just be added to a folder called `phpagebuilder`.
