### ISSUE TITLE
Page Builder view is returning a white blank page.

### ISSUE THREAD

**Issue by Nitinkumarwis** [HansSchouten/PHPageBuilder#93]
I am just trying to view that project that i have saved but when i clicked on view it is returning me with the blank white page can you please help me to resolve this issue.

**Comment by HansSchouten** [comment]
Can you check the URLs you have stored for the pages you created and whether the blocks you dragged to the page have been stored to your database successfully.

**Comment by astutesixface** [comment]
I am also facing same problem

**Comment by Nitinkumarwis** [comment]
Its fixed . Actually i am not using the slash in my url. After adding slash it working good.

**Comment by astutesixface** [comment]
i use the slash, even still i have seeing blank page...
